export const LOAD_REQUEST = 'FLIGHTS/LOAD_REQUEST';
export const LOAD_SUCCESS = 'FLIGHTS/LOAD_SUCCESS';
export const LOAD_FAILURE = 'FLIGHTS/LOAD_FAILURE';

export const ADD_TO_FAVOURITES = 'FLIGHTS/ADD_TO_FAVOURITES';
export const ADD_TO_FAVOURITES_AFTER_FETCHING = 'FLIGHTS/ADD_TO_FAVOURITES_AFTER_FETCHING';
export const REMOVE_FROM_FAVOURITES = 'FLIGHTS/REMOVE_FROM_FAVOURITES';
export const MAKE_FAVOURITE = 'FLIGHTS/MAKE_FAVOURITE';
export const MAKE_UNFAVOURITE = 'FLIGHTS/MAKE_UNFAVOURITE';